"""Create chats and messages

Revision ID: 2df7d5cd2851
Revises: 66f7a77410d5
Create Date: 2026-07-06 16:55:38.213223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df7d5cd2851'
down_revision = '66f7a77410d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
